repo:
- '*'

templates:
- any: ['examples/*']
- any: ['developer/examples/*']

core-vpc:
- builder/vpc/**/*

core-classic:
- builder/classic/**/*

provisioner:
- provisioner

scripts:
- scripts

version:
- verison
