// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package ibmcloudexport

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	PackerBuildName     *string           `mapstructure:"packer_build_name" cty:"packer_build_name" hcl:"packer_build_name"`
	PackerBuilderType   *string           `mapstructure:"packer_builder_type" cty:"packer_builder_type" hcl:"packer_builder_type"`
	PackerCoreVersion   *string           `mapstructure:"packer_core_version" cty:"packer_core_version" hcl:"packer_core_version"`
	PackerDebug         *bool             `mapstructure:"packer_debug" cty:"packer_debug" hcl:"packer_debug"`
	PackerForce         *bool             `mapstructure:"packer_force" cty:"packer_force" hcl:"packer_force"`
	PackerOnError       *string           `mapstructure:"packer_on_error" cty:"packer_on_error" hcl:"packer_on_error"`
	PackerUserVars      map[string]string `mapstructure:"packer_user_variables" cty:"packer_user_variables" hcl:"packer_user_variables"`
	PackerSensitiveVars []string          `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables" hcl:"packer_sensitive_variables"`
	IBMApiKey           *string           `mapstructure:"api_key" cty:"api_key" hcl:"api_key"`
	Region              *string           `mapstructure:"region" cty:"region" hcl:"region"`
	Endpoint            *string           `mapstructure:"vpc_endpoint_url" cty:"vpc_endpoint_url" hcl:"vpc_endpoint_url"`
	IAMEndpoint         *string           `mapstructure:"iam_url" cty:"iam_url" hcl:"iam_url"`
	ImageID             *string           `mapstructure:"image_id" cty:"image_id" hcl:"image_id"`
	ImageExportJobName  *string           `mapstructure:"image_export_job_name" cty:"image_export_job_name" hcl:"image_export_job_name"`
	StorageBucketName   *string           `mapstructure:"storage_bucket_name" required:"true" cty:"storage_bucket_name" hcl:"storage_bucket_name"`
	Format              *string           `mapstructure:"format" cty:"format" hcl:"format"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"packer_build_name":          &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"packer_builder_type":        &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"packer_core_version":        &hcldec.AttrSpec{Name: "packer_core_version", Type: cty.String, Required: false},
		"packer_debug":               &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"packer_force":               &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"packer_on_error":            &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"packer_user_variables":      &hcldec.AttrSpec{Name: "packer_user_variables", Type: cty.Map(cty.String), Required: false},
		"packer_sensitive_variables": &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"api_key":                    &hcldec.AttrSpec{Name: "api_key", Type: cty.String, Required: false},
		"region":                     &hcldec.AttrSpec{Name: "region", Type: cty.String, Required: false},
		"vpc_endpoint_url":           &hcldec.AttrSpec{Name: "vpc_endpoint_url", Type: cty.String, Required: false},
		"iam_url":                    &hcldec.AttrSpec{Name: "iam_url", Type: cty.String, Required: false},
		"image_id":                   &hcldec.AttrSpec{Name: "image_id", Type: cty.String, Required: false},
		"image_export_job_name":      &hcldec.AttrSpec{Name: "image_export_job_name", Type: cty.String, Required: false},
		"storage_bucket_name":        &hcldec.AttrSpec{Name: "storage_bucket_name", Type: cty.String, Required: false},
		"format":                     &hcldec.AttrSpec{Name: "format", Type: cty.String, Required: false},
	}
	return s
}
