name: Create IBM Packer Plugin Binary

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

# In case OWASP ZAP Full Scan is required
#   zap_scan:
#     runs-on: ubuntu-latest
#     steps:
#       - name: ZAP Scan
#         uses: zaproxy/action-full-scan@v0.3.0
#         with:
#           target: 'https://www.zaproxy.org/'

  build:
#     # Runs on Multiple OS
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [ubuntu-latest, windows-latests, macOS-latest]

    # Runs Only on Ubuntu OS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.0.0

    - name: Unshallow
      run: git fetch --prune --unshallow

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Setup Packer
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: "latest"

    - name: Install packer-sdc
      run: go install github.com/hashicorp/packer-plugin-sdk/cmd/packer-sdc@latest

    - name: Set Up Dependencies
      run: |
        go mod tidy
        go mod vendor
        go generate ./builder/ibmcloud/...
        go mod vendor

    - name: Build IBM Cloud Packer Plugin binary
      run: go build .

    - name: Run `packer init`
      id: init
      run: |
        packer init -upgrade examples/build.vpc.centos.pkr.hcl

    - name: Run `packer validate`
      id: validate
      run: |
        packer validate -var-file="examples/variables.pkrvars.hcl" examples/build.vpc.centos.pkr.hcl
